// Readiness Snapshot Service
// Pure functions for generating readiness snapshots based on coverage metrics
// No React imports, no UI - business logic only

import { getReadinessStatus } from '@/data/readinessThresholdsConfig';
import type { ReadinessStatus } from '@/data/readinessThresholdsConfig';
import type { CoverageMetrics } from './coverageService';

export interface ReadinessSnapshot {
  snapshot_id: string;
  coop_id: string;
  readiness_status: ReadinessStatus;
  snapshot_reason: string;
  created_at?: string;
}

/**
 * Generate a readiness snapshot based on coverage metrics
 * 
 * @param cooperativeId - The cooperative ID
 * @param coverageMetrics - Coverage metrics for the cooperative
 * @returns Readiness snapshot object
 */
export function generateReadinessSnapshot(
  cooperativeId: string,
  coverageMetrics: CoverageMetrics
): ReadinessSnapshot {
  const coveragePercentage = coverageMetrics.coverage_percentage;
  const readinessStatus = getReadinessStatus(coveragePercentage);
  
  // Generate snapshot reason
  const snapshotReason = `Coverage: ${coveragePercentage.toFixed(1)}% (${coverageMetrics.required_docs_present}/${coverageMetrics.required_docs_total} documents)`;
  
  return {
    snapshot_id: '', // Will be generated by database
    coop_id: cooperativeId,
    readiness_status: readinessStatus,
    snapshot_reason: snapshotReason,
    created_at: new Date().toISOString(),
  };
}

