// TypeScript types for Value Tracking System

export type ProgressStatus = 'draft' | 'submitted' | 'reviewed';

export interface BaselineMeasurement {
  id: string;
  cooperativeId: string;
  measuredAt: string;
  measuredBy?: string;
  
  // Administrative time (hours/week)
  hoursMemberManagement?: number;
  hoursMeetingOrganization?: number;
  hoursReportPreparation?: number;
  hoursCertificationTracking?: number;
  hoursMemberCommunication?: number;
  hoursDocumentManagement?: number;
  totalAdminHoursPerWeek?: number;
  
  // Commercial efficiency
  avgDaysToNegotiatePrice?: number;
  percentageSalesAtOptimalPrice?: number;
  marketPriceAccessFrequencyPerWeek?: number;
  exportDocumentPrepDays?: number;
  
  // Compliance and certifications
  missedDeadlines12Months?: number;
  auditPreparationDays?: number;
  lostMisplacedDocuments?: number;
  delayedSubmissions?: number;
  
  // Security and risks
  securityIncidents12Months?: number;
  dataLossIncidents?: number;
  internalCommunicationProblemsPerMonth?: number;
  financialRecordErrors?: number;
  
  notes?: string;
  createdAt?: string;
}

export interface MonthlyProgress {
  id: string;
  cooperativeId: string;
  progressMonth: string; // ISO date string (first day of month)
  submittedBy?: string;
  submittedAt?: string;
  
  // Administrative time savings
  currentAdminHoursPerWeek?: number;
  baselineAdminHoursPerWeek?: number;
  hoursReduction?: number;
  percentageReduction?: number;
  automatedTasksCount?: number;
  simplifiedProcessesCount?: number;
  
  // Commercial improvement
  avgPriceImprovementPercentage?: number;
  baselineAvgPrice?: number;
  currentAvgPrice?: number;
  negotiationTimeReductionDays?: number;
  newOpportunitiesIdentified?: number;
  premiumBuyersContacted?: number;
  
  // Compliance and certification
  deadlinesMet?: number;
  totalDeadlines?: number;
  auditPrepTimeReductionDays?: number;
  documentsOrganizedAutomaticallyPercentage?: number;
  autoGeneratedReports?: number;
  
  // Security and reliability
  securityIncidentsPrevented?: number;
  successfulAutoBackups?: number;
  internalCommunicationImprovementPercentage?: number;
  dataErrorReductionPercentage?: number;
  
  // Member satisfaction
  memberSatisfactionScore?: number; // 1-10
  activePlatformUsersPercentage?: number;
  improvementSuggestionsReceived?: number;
  problemsReported?: number;
  
  // Corrective actions needed
  additionalTrainingRequired?: boolean;
  missingFeaturesIdentified?: string;
  technicalSupportNeeded?: boolean;
  configurationAdjustments?: string;
  
  status: ProgressStatus;
  createdAt?: string;
  updatedAt?: string;
}

export interface ValueMetric {
  id: string;
  cooperativeId: string;
  metricMonth: string; // ISO date string
  calculatedAt: string;
  
  // Efficiency metrics
  adminTimeSavedHours?: number;
  adminCostSavedUsd?: number;
  deadlineCompliancePercentage?: number;
  errorReductionPercentage?: number;
  
  // Economic impact
  priceImprovementUsd?: number;
  newRevenueOpportunitiesUsd?: number;
  totalEconomicImpactUsd?: number;
  
  // Capacity building
  digitalLiteracyImprovementScore?: number;
  autonomyIncreasePercentage?: number;
  
  // Security
  securityIncidentsAvoided?: number;
  dataIntegrityScore?: number;
  
  createdAt?: string;
}

export interface ImpactSummary {
  cooperativeId: string;
  baseline?: BaselineMeasurement;
  latestProgress?: MonthlyProgress;
  latestMetrics?: ValueMetric;
  totalTimeSaved?: number;
  totalEconomicImpact?: number;
  improvementPercentage?: number;
}

